


 @Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJOUkYiLCJzdWIiOiJhdXNmLTAwMSIsImV4cCI6MTc3NzgxOTUxNywiaWF0IjoxNzc3ODE1OTE3LCJqdGkiOiJhdXNmLTAwMS0xNzc3ODE1OTE3ODgwOTc4OTU0Iiwic2NvcGUiOiJudWRtLXNkbSIsIm5mVHlwZSI6IkFVU0YifQ.ogfIFRP08GarKfaEXWmQpcpECvLbsntlUL3mPakvm38


###

Get http://localhost:8001/nudm-sdm/v1/imsi-001010000000002/am-data
Authorization: Bearer {{Token}}